After pulling in all framework code, my test cases failed for the following reason:
File "/automation/tests/extreme_automation_tests/Tests/Pytest/Functional/XIQ/Wired/VOSS/APC-46151/TestCases/test_API_SSH.py", line 58, in setup_class
cls.suiteUkds.onboard_device(cls.xiq, cls.tb.dut1_serial, cls.tb.dut1_os, location)
File "/automation/tests/extreme_automation_tests/Tests/Pytest/Functional/XIQ/Wired/VOSS/APC-46151/Resources/SuiteUdks.py", line 26, in onboard_device
    res = xiq.xflowsmanageSwitch.onboard_switch(serial, os, location=location)
File "/automation/framework/extreme_automation_framework/extauto/xiq/flows/manage/Switch.py", line 116, in onboard_switch
    self.utils.print_info(f"Successfully Onboarded Switch With Serial no. {serial}")
UnboundLocalError: local variable 'serial' referenced before assignment

Looking at the code 'serial' variable was used in the if block of code
but not in the else block of code.

Update the else block of code to use the variable 'switch_serial'
instead of 'serail'