2022-12-13 - Login.py updates (#757)
Multiple XIQ-SE automation tests failing during the XIQ Login process with the error message:
TypeError: argument of type 'NoneType' is not iterable

- xiq/flows/common/Login.py
  -- Update "if" statement to check if the "test_url" variable is null.